// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email as seen by the Tech Handlers MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const info = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "List leads",
  description: "List recent leads (form submissions) captured on the Tech Handlers website. Access follows the signed-in user's admin permissions.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of leads to return."),
    status: z.string().optional().describe("Optional lead status filter (e.g. new, contacted, qualified).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("leads").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool3({
  name: "list_tasks",
  title: "List tasks",
  description: "List tasks visible to the signed-in user, most recently updated first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(25),
    status: z2.string().optional().describe("Optional status filter (e.g. todo, in_progress, done).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("tasks").select("*").order("updated_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_customers_default = defineTool4({
  name: "list_customers",
  title: "List customers",
  description: "List customers of Tech Handlers visible to the signed-in user.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25),
    search: z3.string().optional().describe("Optional case-insensitive substring match on customer name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb3(ctx).from("customers").select("*").order("created_at", { ascending: false }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sqxauvwhnzqapvbkwsgn";
var mcp_default = defineMcp({
  name: "tech-handlers-mcp",
  title: "Tech Handlers MCP",
  version: "0.1.0",
  instructions: "Tools for the Tech Handlers admin workspace. Use `whoami` to verify the signed-in user, `list_leads` to read website form submissions, `list_tasks` for CRM tasks, and `list_customers` for the customer directory. All reads follow the signed-in user's admin permissions and RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_leads_default, list_tasks_default, list_customers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
